name: Learn GA - Test with PyTest
run-name: ${{ github.actor }} running pytests
on: [push]
jobs:
  job-name-0:
    name: Installing SDSMC
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install SDSMC
        run: |
          python3 -m pip install --upgrade pip
          python -m pip install git+https://github.com/sandialabs/distribution-system-model-calibration
          pip install pytest
      - name: Test with PyTest
        run: |
          echo "Testing tests/test_TransformerPairing/test_TransformerPairing_run.py"
          pytest tests/test_TransformerPairing/test_TransformerPairing_run.py